language: node_js
node_js:
- node
before_script:
- npm install -g gulp
script:
- gulp typings
- gulp test
env:
- CXX=g++-5 CC=gcc-5
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-5
        - g++-5
        - clang
