language: node_js
node_js:
- "node"
before_script:
- npm install -g gulp
script:
- gulp test
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi; npm install
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-5
        - g++-5
        - clang
